# change source and team
# source: https://github.com/rht-labs/tech-exercise.git
source: https://gitlab-ce.apps.cluster-ndfxh.ndfxh.sandbox1204.opentlc.com/will/tech-exercise.git
team: will
release: ci-cd

applications:
  # Tooling to support CI/CD
  - name: ubiquitous-journey
    enabled: true
    source_path: "."
    helm_values:
      - ubiquitous-journey/values-tooling.yaml

  # Test app of app
  - name: test-app-of-pb
    enabled: true
    source_path: "."
    helm_values:
      - pet-battle/test/values.yaml

  # Staging App of Apps
  - name: staging-app-of-pb
    enabled: true
    source_path: "."
    helm_values:
      - pet-battle/stage/values.yaml
