release: "stage"
source: "http://nexus:8081/repository/helm-charts/"
##############
# Argo Apps declaration
#############
applications:
  # Keycloak

  # Pet Battle Apps
  pet-battle-api:
    name: pet-battle-api
    enabled: true
    source: https://petbattle.github.io/helm-charts # http://nexus:8081/repository/helm-charts
    chart_name: pet-battle-api
    source_ref: 1.2.1 # helm chart version
    values:
      image_name: pet-battle-api
      image_version: latest # container image version
      hpa:
        enabled: false
  pet-battle:
    name: pet-battle
    enabled: true
    source: http://nexus:8081/repository/helm-charts 
    chart_name: pet-battle
    source_ref: 1.0.6 # helm chart version
    values:
      image_version: latest # container image version
      config_map: '{ "catsUrl": "https://pet-battle-api-will-stage.apps.cluster-ndfxh.ndfxh.sandbox1204.opentlc.com", "tournamentsUrl": "https://pet-battle-tournament-will-stage.apps.cluster-ndfxh.ndfxh.sandbox1204.opentlc.com", "matomoUrl": "https://matomo-will-ci-cd.apps.cluster-ndfxh.ndfxh.sandbox1204.opentlc.com/", "keycloak": { "url": "https://keycloak-will-stage.apps.cluster-ndfxh.ndfxh.sandbox1204.opentlc.com/auth/", "realm": "pbrealm", "clientId": "pbclient", "redirectUri": "http://localhost:4200/tournament", "enableLogging": true } }'
