applications:
  # Bootstrap Project
  - name: bootstrap
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: bootstrap-project
    source_ref: "1.0.1"
    values:
      serviceaccounts: ""
      # student is the GROUP NAME in IDM
      bindings: &binds
        - name: student
          kind: Group
          role: admin
        - name: jenkins
          kind: ServiceAccount
          role: admin
          namespace: will-ci-cd
      namespaces:
        - name: will-ci-cd
          bindings: *binds
          operatorgroup: true
        - name: will-dev
          bindings: *binds
          operatorgroup: true
        - name: will-test
          bindings: *binds
          operatorgroup: true
        - name: will-stage
          bindings: *binds
          operatorgroup: true

  # Jenkins
  - name: jenkins
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-1.0.6"
    values:
      buildconfigs:
        # Jenkins S2I from Red Hat Labs
        - name: jenkins
          strategy_type: "Source"
          source_repo: https://github.com/rht-labs/s2i-config-jenkins.git
          source_repo_ref: master
          source_context_dir: '/'
          builder_image_kind: "DockerImage"
          builder_image_name: quay.io/openshift/origin-jenkins
          builder_image_tag: "latest"
        # Jenkins agents for running builds etc
        # default names, versions, repo and paths set on the template
        - name: jenkins-agent-npm
        - name: jenkins-agent-mvn
        - name: jenkins-agent-helm
        - name: jenkins-agent-argocd
      deployment:
        env_vars:
          - name: GITLAB_DEFAULT_BRANCH
            value: 'main'
          - name: GITLAB_HOST
            value: 'gitlab-ce.apps.cluster-ndfxh.ndfxh.sandbox1204.opentlc.com'
          - name: GITLAB_GROUP_NAME
            value: 'will'
          - name: GIT_SSL_NO_VERIFY
            value: "true"
          - name: JAVA_ARGS
            value: '-Dorg.jenkinsci.plugins.gitclient.GitClient.untrustedSSL=true'
          - name: Hello
            value: 'World'
      persistence: false
      source_secrets:
        - name: nexus-password
          username: admin
          password: admin123

  # Nexus
  - name: nexus
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonatype-nexus
    source_ref: "1.1.10"
    values:
      includeRHRepositories: false
      service:
        name: nexus



  # Sealed Secrets
  - name: sealed-secrets
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: helper-sealed-secrets
    source_ref: "1.0.3"
    values:
      secrets:
        # Additional secrets will be added to this list along the exercises.
        - name: git-auth
          type: kubernetes.io/basic-auth
          annotations:
            tekton.dev/git-0: https://gitlab-ce.apps.cluster-ndfxh.ndfxh.sandbox1204.opentlc.com
          labels:
            credential.sync.jenkins.openshift.io: "true"
          data:
            username: AgBY3H7kU0/KtohcqpKu6E3tltY1Gs8f8lgagh5KRBIOD50MhTak2h5q3OnHQyK5pHrXy6bCtAgkLO1IHEDQaJ6i6fQn6NxaErW69BirOQFx14OHIK4dhRi8lfvxaR3VLe0v9NA1kSj9tQ1lyrWHtgh5MNJifpuC63dg2TT3M3JrxTIFwiUDcygkgiC+64fcAaJeem682/jr8md4MJC/yrB3DSFYiCwnVN3P/zu4q2LoQdqnEXdZIWsiHBjuGbY1ZyhbjcFeiLuk2yi0EJabc7/I0X+oilfAoE4+Oo0pBELRY0kfLV61S6O8cVwgdtnXBulmt15u7ftYPpvvzIMoB/q5bg2zgo/jLqFTjibuLN3Nu7wDeMYzD0599jxyURtRwgwKvT3xmKJBChLTQFhV+BLkx1E0fbWzZkjgWT6QSDQEEx7y2Kpl47L6qP99I6/bNKYY4DzFcUBZRpgubnGKBeNOmhQ6FDKYawjDiEmeUSQrxKBp2t5pC73+o10iazb5u8w8A1xCfujggHxmXV8wYUCKBBuYUnja/x7RYlddEplvKNKrAMMtGqr7YcRLFkEIu3JjrSeL55cNWQ3PC+rtjdKrI77lK+1SwFqYEkCLzUjrcCy9Sg0ui5+hah8R/p+25mZOfBCrN3A1hEMCoEUnOsQH1mgtewnAzuyiN8Ukko+Gq+qxQB5z/3WIKTORgumIlfy8GMxxuQ==
            password: AgAkaj0v50rlBmAWLkQwho1DWLd+9yPnurfk+o4llaXdXD8an+rnLRrfg+6js3LGRZH9l7RKqHY+vs34xyYGAaCtVAgjgKeNg9m2q4lENMtBwz9O0uLxnURjdBm1tAOkcpY+XUPTa3I5J2qkYfTyu+lJUnaTPfB1jF28yIng3vXs+FK8v7kXH1a7JnBFHbpfnNlKvNjyvDV7IK0g0iokDyjLyK4zfiFENGrliIxGT6iCu4JlxIo3WCEFS1CHK4ah/mNANcOggUiUYiPKlXqnsgMfEq0g+yKY6vWZH9NPPCACYg9tpAo8u8bZxStHu2S/VuhK3134ynho/cWZ7m3+ciOhbb66b8AY56yqzKwUzJ4LkTMYBTcwi9/nfMpFB/ckdisDTqKN9OTxSMLOsl6WM9bYUzSfMUZi8/NbSD84+kEuHl95hjkKPdwiLyvOOgeoNU1ZtFd3ecM5e0bVlgDWgI2WTBM9KlyQr32UX61iMYRPj4EWdm8M8qY+DT0Qt7fssNa3JF6kXNJKkd7yAdVV7lPOixSDUacfHKHv9oMVxyTjDSEQgXv/Blc3nT59YIsCKllJGxpXZ/PK0Znzm1kCXhXD0WIhWAhsEgPwG9gvdgxQK3DiZUmCNrE7XD8rq9gFzBaLj2h1n2FKBFJoS00Am4uWwiri5R4I3c3YK4TW+LEfAQ0rYWyjE2mYcGg/USu5Wm8V9L17gdMTPBPCqlmRBy8oj2dTYQ==
        - name: sonarqube-auth
          type: Opaque
          labels:
            credential.sync.jenkins.openshift.io: "true"
          data:
            username: AgAVKa3YcgWjR0i5gre8gKFuBoDkfE9EhqNxAVEWanw3DFa8CpwCNl7nRW9f6BGVzzDNDig1J6tiLIUyaYStYa8P/iCecR2ljFrkLP4vLTcEHF6bn4jS6eE4taxCACqUTfaCwOyZEZYcMQdmpk/QobjWgdsW42anTZnmRrOKosBhiwuAa+6DsvtzGvwvoUn2J/+9IX3K6rpEDQYsQ0BzKIQ9P/opgslcy4MakN9tvGb43IVkuFa18p3tsXtXR6Y+34qIeJ0WXYAtSImqZs3DTwoJTFc1qTFGImopw4DudBmxAQSltkMAZhTnsws0WUslhDTGKOCwlim2GFMNwHY4SPaVyyzwRhI656bVG/o0sCD8HiPeE9UaRXGFiMTqXfknOgQ+L6UdTUtum4zuB+j+Z1rK/Dfc0Z0ZH2FlekrRz3ARvW5JM1Q1pRRnA96KpDV32JctOEBR+Cig3pKJ544E5PEOizLPggb4xJ6dqAgq5DZ1V/g8IwR2zrhbgHeDmvc/NbFNW1xHhoaigw5qdK2Z4qH3dlD1xAp6ggWt2qf2ZmZKsVkE2X5PbyLnmms1AB+WGGunVBCd2TMk8w6V3AQdRpVXQHP6bVn+wPgIsjRJUxI9URiVyEBbYNucBXZ6NDEdQVyG53LNJu8GgoZ2ciqk7/jeChr/y2Qg+Z+et8/ryvTLp6pcR6Av3M2WiVd7vAmnsnNI6/IPQw==
            password: AgC6HX25buKbMSTTK9H9D9ZcvgS2TyQS7zmPTCg9srOUjPhBfysQrjqiy2k1QlCfvPDTQilAbjd15OkbQhirlqB3t8bWiyqLJyMnVBlY3scGjR2og3lygcWQs3V9p5kzMvHNX65K2inYXBLDzCRr0TM7t7Luf2UP+8umE6Pt1/wmWklpJSQlQgKa2oPCYgHUWaz1Vgkmg8yFA50lXdt17EW3eXGpgrPnJipMYuYMGl5uJPsOEh/R0k6r/dfIOiA4GV1XqFAVeYrpVsUhAk7ELbZyYm2cSQ0aqy1Zyd/cQQpmQ1zoaakxUx4X08y9o45YssMglNd4J6CJFGDwPnjYh7ZIxAFg9w0khP6ISPUkJ9YqLXD8cXo21F1r5U+mfmRoF0lyQEDXSspSlNtdpUwSJYwyC6JApHNKj4N19A3wLipRxzFvJKhrrXpQEAR+pR89exhlohj9NZzDpUSahmSmhPrU16fjcwQ+7Y/zrCd2bhXxZjH/FNZvIHXNjKclvSWnFrpZXJQjlcnCLQOrDp/aMGv33FD+iqIFe/uAs8jqTJ/IVUkljhErxQl3O2AuWqaHYzoXWE7fz9GI4B/HL16YgSaXNrcCow69tLwfm461UaU+jqUVRQPV1zYXL3HCFPvX5Rs42CMFPJ1ptWJtuwCmyRD26KPzdHwyj9nbE/eZ8YLBAIYfoEXNzh8m923P2cN03CCgRYpm607RuQ==
            currentAdminPassword: AgB0boNq6XjfLHakbYeRIbzj1GNVCfsSQ68ixZksEu7n7OjbYXoqll+TMPV0pJb7SCOnLpjLWdcqKEVlIoCMgX+HjqFYgts8kUj5upfRqzF3Uw2ePDCnQuz4Y00sp6SyyrEdgjJygxVvi+2ogEW5ssV64YtZoAaHck1mbeOTCbh4sMximawMLAAk0VUFEyUtxo41v4ZFt6olL9+q2GL/m4bG6F5+9kFX3t65a4BtvfRYVvde6mHG0E0oQw2qePoGr0dO+D8nZjX9UVTDWSQ1rZrEFEFPp09E+/3FsDjdEmNnacQ4YltcpWoldNpYv07ViAacJTGUlqbHVNtylv+fwMGAooP3AOLrk1ttiLpx1c+5Dv6kB5FMtPtSsCFtkV6j9Yx+/37EfL4t8wy4sAx/m4BF+JVE18zWmlb4YL9O60WX7nAyKXOm3priB/6r1HTTUKaafhaqZJh8DHbvbaHQDIYaEPJNKPYX7FLNVX2IX6FOJXP+zwPi4U+ecg32lk5Tb5tFkFJyxtF7yKM/YLABgC14loRRZxwFfnAgWz2+TKe7p+FonpMohBmX4s+qi079LXOiiQPtEtkAc4IC+rioHUqsmXu122M+Y98y3riSX8IRB/FWtz+mrOkA2NbFW8B9UGOJmzXRoxVHTLGkpk97rR3x1UElv5KDHm39M/IR1GF+EY2J/+qqTqC3eo3OiqcKJIBMWM2d7Q==
    



  # Tekton Pipelines
  - name: tekton-pipeline
    enabled: true
    source: "https://gitlab-ce.apps.cluster-ndfxh.ndfxh.sandbox1204.opentlc.com/will/tech-exercise.git"
    source_ref: main
    source_path: tekton
    values:
      team: will
      cluster_domain: apps.cluster-ndfxh.ndfxh.sandbox1204.opentlc.com
      git_server: gitlab-ce.apps.cluster-ndfxh.ndfxh.sandbox1204.opentlc.com



  # Sonarqube
  - name: sonarqube
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonarqube
    source_ref: "0.1.0"
    values:
      account:
        existingSecret: sonarqube-auth
      initContainers: true
      plugins:
        install:
          - https://github.com/checkstyle/sonar-checkstyle/releases/download/9.2/checkstyle-sonar-plugin-9.2.jar
          - https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.8/sonar-dependency-check-plugin-2.0.8.jar



  # Grafana


  # Allure


  # Matomo
